sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t s4bb4n/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true s4bb4n/docker-react npm run test
